In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
food = pd.read_csv('../artifacts/Sri Lanka Food Composition Table .csv')

In [12]:
food.head()

,FCT source,drfoodlistcode,drfoodlistdesc,Recipe/Single food item,Energy (kcal),Protein (g),Total fats (g),Total carbohydrates (g),Fiber (g),Starch (g),...,Phosphorus (mg),Potassium (mg),Sodium (mg),Selenium (mcg),Retinol (mcg),Saturated fatty acids (g),Mono-unsaturated fatty acids (g),Poly-unsaturated fatty acids (g),Free sugars (g),Unnamed: 36
0,"ASEAN FCT #AAP1 Beer, pale pilsen",10010001.0,BEER,S,43.0,0.0,0.46,3.55,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wayamba 2022 SPIRITS,10010002.0,"LIQUOR, ARAK",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wayamba 2022 SPIRITS,10010003.0,"LIQUOR, KASIPPU",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wayamba 2022 SPIRITS,10010004.0,"LIQUOR, TODDY, COCONUT",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Wayamba 2022 SPIRITS,10010006.0,"LIQUOR, TODDY, KITUL",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Data Preprocessing

In [13]:
food.shape

(1641, 37)

In [14]:
food.duplicated().sum()

np.int64(874)

In [15]:
food.isnull().sum()

FCT source                            896
drfoodlistcode                        875
drfoodlistdesc                        875
Recipe/Single food item               875
Energy (kcal)                         885
Protein (g)                           885
Total fats (g)                        885
Total carbohydrates (g)               889
Fiber (g)                             924
Starch (g)                            949
Cholesterol (mg)                      942
Calcium (mg)                          888
Magnesium (mg)                        917
Iron (mg)                             888
Zinc (mg)                             894
Thiamin (mg)                          897
Riboflavin (mg)                       890
Niacin (mg)                           891
Vitamin B6 (mg)                       895
Vitamin B12 (mcg)                    1047
Folate, ug                            896
Vitamin C (mg)                        902
Retinol Activity Equivalents (ug)     901
Vitamin E (ug)                        942
total n-6 fas (% of energy)          1277
total n-3 fas (% of energy)          1277
Vitamin B5 (mg)                      1272
Phosphorus (mg)                      1265
Potassium (mg)                       1269
Sodium (mg)                          1270
Selenium (mcg)                       1275
Retinol (mcg)                        1608
Saturated fatty acids (g)            1497
Mono-unsaturated fatty acids (g)     1500
Poly-unsaturated fatty acids (g)     1499
Free sugars (g)                      1411
Unnamed: 36                          1641
dtype: int64

In [16]:
food = food.drop_duplicates().reset_index(drop=True)

In [17]:
food = food.drop(columns=['Unnamed: 36'])

In [18]:
food = food.rename(columns={'drfoodlistdesc': 'Food'})

In [19]:
food = food.rename(columns={
    'Energy (kcal)': 'Calories',
    'Total fats (g)': 'Fat',
    'Total carbohydrates (g)': 'Carbs',
    'Protein (g)': 'Protein'
})

In [20]:
food['Food'].str.contains('GARLIC', case=False, na=False).sum()
food['Food'].str.contains('GINGER', case=False, na=False).sum()
food['Food'].str.contains('GINKGO', case=False, na=False).sum()

np.int64(0)

In [22]:
food[food['Food'].str.contains('GAR', case=False, na=False)].head(20)

,FCT source,drfoodlistcode,Food,Recipe/Single food item,Calories,Protein,Fat,Carbs,Fiber (g),Starch (g),...,Vitamin B5 (mg),Phosphorus (mg),Potassium (mg),Sodium (mg),Selenium (mcg),Retinol (mcg),Saturated fatty acids (g),Mono-unsaturated fatty acids (g),Poly-unsaturated fatty acids (g),Free sugars (g)
17,Calculated from recipes table,10020209.0,"LEMON OR LIME JUICE,FRESH, W/ WATER & SUGAR",R,4.269674,0.030745,0.063151,0.898937,0,0.000000,...,0.008309,0.833431,11.971264,0.080982,0.001724,NaN,17.532804,3.96607,28.999758,0.218537
44,Wayamba 2022 CURRANT BUN,11010005.0,"BUN, ICED OR SUGAR GLAZED",S,280.000000,8.000000,5.600000,52.600000,0,36.600000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Wayamba 2020 MARGARINE,12010005.0,MARGARINE,S,739.000000,0.200000,81.600000,1.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,Calculated from recipes table,14030002.0,"FRUIT SALAD, W/ ADDED SUGAR",R,72.360001,0.655200,0.393600,16.338400,2.4575999,1.692000,...,0.273600,13.396800,207.200000,2.512000,4.550400,NaN,128.433610,104.85600,80.548798,9.357600
295,Calculated from recipes table,15010107.0,"CHICK PEAS, BOILED, W/ SCRAPED COCONUT & SUGAR",R,216.572388,10.196964,7.407123,26.139288,14.66397858,18.147846,...,1.271175,128.676209,372.125855,17.736952,25.519932,NaN,NaN,NaN,NaN,0.391725
450,Calculated from recipes table,18040013.0,FLATTENED RICE W/ SCRAPED COCONUT & SUGAR,R,330.720001,5.535182,7.126629,60.588902,3.809961319,45.796078,...,0.378787,148.836060,135.117706,6.552561,3.828617,NaN,NaN,NaN,NaN,0.195007
470,NaN,19010013.0,VISKIRINGA (SUGAR GLAZED RUSK),S,490.000000,7.000000,20.000000,71.000000,1,NaN,...,NaN,NaN,45.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,"Wayamba 2020 CASSAVA CHIPS,FRIED,SUGAR COATED",19060003.0,"CASSAVA CHIPS,FRIED,SUGAR COATED",R,287.000000,0.360000,8.800000,53.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
704,"Wayamba 2022 GARLIC, CURRY W/ COCONUT MILK",20080501.0,"GARLIC, W/ COCONUT MILK",R,105.000000,3.600000,5.300000,11.400000,2.8,7.700000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
758,"USDA FDC ID 169655 Sugars, granulated",96000003.0,SUGAR,S,387.000000,0.000000,0.000000,100.000000,0,NaN,...,0.000000,0.000000,2.000000,1.000000,0.600000,0.0,0.000000,0.00000,0.000000,NaN